services:
  - type: web
    name: learn-render-app
    env: node
    plan: free
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
